version: "3.9"

services:
  leagueify-webapp:
    container_name: leagueify-webapp
    image: ghcr.io/leagueify/leagueify:latest
    environment:
      DATABASE_URI: mongodb://database:27017/leagueify
      DATABASE_USER: leagueify
      DATABASE_PASS: password
    ports:
      - 80:3000
    restart: always

  leagueify-database:
    container_name: leagueify-database
    image: mongo:6.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: leagueify
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - 27017
    restart: always
